### ISSUE TITLE
componentDidUpdate

### ISSUE THREAD

**Issue by ViktorSvertoka** [EuJinnLucaShow/goit-react-hw-03-phonebook#3]
Смотри что нарыл в GPT 😅

componentDidUpdate(_, prevState) - это перемога!

В JavaScript и во многих фреймворках, включая React, принято использовать нижнее подчеркивание (underscore) в качестве конвенции для обозначения аргумента, который не будет использоваться в функции или методе.

В методе componentDidUpdate первый параметр, обычно называемый prevProps, содержит предыдущие значения свойств компонента, которые были переданы до обновления. Однако, если в данном методе не требуется использовать предыдущие пропсы, разработчики часто используют нижнее подчеркивание в качестве плейсхолдера для неиспользуемого параметра. Это помогает подчеркнуть факт, что параметр не имеет значения или не используется в данной функции.

Таким образом, использование нижнего подчеркивания вместо имени переменной является просто соглашением и помогает читателям кода понять, что значение этого параметра не используется внутри метода componentDidUpdate.

**Comment by EuJinnLucaShow** [comment]
Very nice.
